# Base configs
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Shots by Pushpinder Pal Singh"
subtitle: "A chapter from my life"
author:  "Pushpinder Pal Singh"
header:
 title: "Shots"
 subtitle: "by Pushpinder Pal Singh"
footer:
 name: "Hey there, I am Pushpinder Pal Singh "
 bio: "a pre-final year computer engineering student at the Netaji Subhas University of Technology, New Delhi. I am an iOS developer with experience in creating apps in AR amongst other things. To me a photo says a thousand words and I like writing chapters of my life"
social_urls:
  twitter: "https://twitter.com/pushpinderpal_"
  instagram: "https://www.instagram.com/pushpinderpalsingh_/"
  linkedin: "https://www.linkedin.com/in/pushpinderpalsingh/"
  github: "https://github.com/pushpinderpalsingh"

theme: jekyll-theme-cayman